Text summarization app | Lev Golofastov
lev-golofastov/mini-ml-app pull request #1
Opened 2022-12-14 13:05 UTC by lev-golofastov

Simple Streamlit application for summarizing the given text.
Created as a homework for practice of programming at SPbU by Lev Golofastov.

2022-12-14 16:59 UTC, SpirinEgor requested changes
Good, but let's improve interface for better usage experience!

2022-12-14 16:59 UTC, SpirinEgor commented on src/main.py
> +	summarizer = pipeline(
What padding do you use? It seems that there are 8 spaces instead of the classic 4 🧐

2022-12-14 16:59 UTC, SpirinEgor commented on src/main.py
> +		device=0 if torch.cuda.is_available() else -1,
Use `"cuda"` or `"cpu"` for the device name.

```python
device = "cuda" if torch.cuda.is_available() else "cpu"
```

2022-12-14 16:59 UTC, SpirinEgor commented on src/main.py
> +	result = summarizer(text_to_analyze)
You can customize results by passing `min_length`, `max_length`, `beam_search`, etc. See [`#generate`](https://huggingface.co/docs/transformers/main_classes/text_generation) for all parameters.

You can add sliders in the interface, so a user may set up a generation algorithm.

2022-12-14 16:59 UTC, SpirinEgor commented on src/main.py
> +	st.write(sample)
You can specify this text as a placeholder for the text area. So the user can either generate a summary for it or replace it with a new one.

2022-12-15 19:02 UTC, lev-golofastov commented on src/main.py
> +		device=0 if torch.cuda.is_available() else -1,
Fix in cecca7f

2022-12-15 19:03 UTC, lev-golofastov commented on src/main.py
> +	st.write(sample)
Fix in 3f6a369

2022-12-15 19:03 UTC, lev-golofastov commented on src/main.py
> +	summarizer = pipeline(
Fix in daf1c2f

2022-12-15 20:29 UTC, lev-golofastov commented on src/main.py
> +	result = summarizer(text_to_analyze)
Add in 52e61b3

2022-12-20 12:58 UTC, SpirinEgor approved these changes
👍

2022-12-20 12:58 UTC, SpirinEgor commented on src/main.py
> +    )
This will reload the pipeline on each generation. Try to avoid this in future work.

2022-12-21 06:21 UTC, lev-golofastov commented on src/main.py
> +    )
Thank you! I will try my best :)

2022-12-21 06:22 UTC, merged